hostname: Core2
ip_routing: true
loopback_interfaces:
  - name: Loopback0
    ip_address: 22.22.22.22/32
ethernet_interfaces:
- name: Ethernet1
  type: routed
  mtu: 1500
  ip_address: 10.220.0.2/30
  ospf_area: 0
  ospf_network_point_to_point: yes


- name: Ethernet2
  type: routed
  mtu: 1500
  ip_address: 10.220.0.13/30
  ospf_area: 0
  ospf_network_point_to_point: yes
- name: Ethernet3
  type: routed
  mtu: 1500
  ip_address: 10.220.0.17/30
  ospf_area: 0
  ospf_network_point_to_point: yes

router_ospf:
  process_ids:
    - id: 10
      router_id: 22.22.22.22